# Generated by Django 5.1.2 on 2024-10-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="authorbook",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="availablebooks",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="bookgenre",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="purchases",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="reader",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"managed": True},
        ),
    ]
